project_file: "."

pca_model_file: "Models/pca_transformer.joblib"
unitig_to_index_file: "Models/unitig_to_index_xg.pkl"

models_directory: "Models"

files:
  strain_file: "data/strain_names.csv"
  circularity_data: "data/dependent_median_circularity_ML.csv"
  size_data: "data/dependent_median_size_ML.csv"
  opacity_data: "data/dependent_median_opacity_ML.csv"
  amr_data: "data/combined_amr_kleborate_ast_with_14thAug_iris.tsv"
  gene_antibiotics: "data/resist_genes.json"
  reference_gbff: "data/pan_genome_reference.fa"
  all_fsa: "data/resistance_genes_seq.fsa"
  vfdb_fas: "data/virulence_genes_seq.fas"
  panaroo_csv: "data/panaroo_gene_presence_absence.csv"
  go_obo_file: "data/go-basic.obo"
  kp_go_tsv: "data/uniprotkb_573.tsv"

directories:
  image_directory: "data/plate_images/"
  iris_directory: "data/iris_measurements/"
