project_file: "/ibex/user/hinkovn/Project_File"

pca_model_file: "/ibex/user/hinkovn/Project_File/Models/pca_500_fitted_model_xg.joblib"
unitig_to_index_file: "/ibex/user/hinkovn/Project_File/Models/unitig_to_index_xg.pkl"

MODEL_PATHS:
  Colistin_0.8ugml:
    XGBoost:
      opacity: "/ibex/user/hinkovn/Project_File/Models/pca_500_opacity_Colistin_0.8ugml"
      circularity: "/ibex/user/hinkovn/Project_File/Models/pca_500_circularity_Colistin_0.8ugml"
      size: "/ibex/user/hinkovn/Project_File/Models/pca_500_size_Colistin_0.8ugml"
    TabNet:
      opacity: "/ibex/user/hinkovn/TabNet/trained_models/TabNet_PCA_opacity_Colistin_0.8ugml.pkl"
      circularity: "/ibex/user/hinkovn/TabNet/trained_models/TabNet_PCA_Circularity_Colistin_0.8ugml.pkl"
      size: "/ibex/user/hinkovn/TabNet/trained_models/TabNet_PCA_Size_Colistin_0.8ugml.pkl"
files:
  strain_file: "/ibex/user/hinkovn/Project_File/data/strain_names.csv"
  circularity_data: "/ibex/user/hinkovn/Project_File/data/dependent_median_circularity_ML.csv"
  size_data: "/ibex/user/hinkovn/Project_File/data/dependent_median_size_ML.csv"
  opacity_data: "/ibex/user/hinkovn/Project_File/data/dependent_median_opacity_ML.csv"
  amr_data: "/ibex/user/hinkovn/Project_File/data/combined_amr_kleborate_ast_with_14thAug_iris.tsv"
  gene_antibiotics: "/ibex/user/hinkovn/Project_File/data/resist_genes.json"
  reference_gbff: "/ibex/user/hinkovn/Project_File/data/reference.gbk.gb"
  all_fsa: "/ibex/user/hinkovn/Project_File/data/resistance_genes_seq.fsa"
  vfdb_fas: "/ibex/user/hinkovn/Project_File/data/virulence_genes_seq.fas"

directories:
  image_directory: "/ibex/user/hinkovn/Project_File/data/plate_images/"
  iris_directory: "/ibex/user/hinkovn/Project_File/data/iris_measurements/"